# Site settings
title: "Mission: Recall"
description: |
    <p>Mission: Recall is a webcomic of poorly remembered pop culture.</p>
    <p>Movies. TV. Games. Music. As I recall.</p>
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://missionrecall.com" # the base hostname & protocol for your site
twitter_username: missionrecall

# Build settings
markdown: kramdown
